// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginOutput struct {
	Token  string  `json:"token"`
	Umpire *Umpire `json:"umpire"`
}

type NewUmpire struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Umpire struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
