type Umpire {
  name: String!
  username: String!
  email: String!
}

input NewUmpire {
  username: String!
  name: String!
  email: String!
  password: String!
}

extend type Mutation {
  createUmpire(input: NewUmpire!): Umpire
}
