// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: rpc_umpire.proto

package brownlowdev

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUmpireRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Fullname string `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CreateUmpireRequest) Reset() {
	*x = CreateUmpireRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_umpire_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUmpireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUmpireRequest) ProtoMessage() {}

func (x *CreateUmpireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_umpire_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUmpireRequest.ProtoReflect.Descriptor instead.
func (*CreateUmpireRequest) Descriptor() ([]byte, []int) {
	return file_rpc_umpire_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUmpireRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUmpireRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *CreateUmpireRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUmpireRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUmpireResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Umpire *Umpire `protobuf:"bytes,1,opt,name=umpire,proto3" json:"umpire,omitempty"`
}

func (x *CreateUmpireResponse) Reset() {
	*x = CreateUmpireResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_umpire_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUmpireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUmpireResponse) ProtoMessage() {}

func (x *CreateUmpireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_umpire_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUmpireResponse.ProtoReflect.Descriptor instead.
func (*CreateUmpireResponse) Descriptor() ([]byte, []int) {
	return file_rpc_umpire_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUmpireResponse) GetUmpire() *Umpire {
	if x != nil {
		return x.Umpire
	}
	return nil
}

var File_rpc_umpire_proto protoreflect.FileDescriptor

var file_rpc_umpire_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x5f, 0x75, 0x6d, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x0c, 0x75, 0x6d, 0x70, 0x69, 0x72, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x6d, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c,
	0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c,
	0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x3c, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x55, 0x6d, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x24, 0x0a, 0x06, 0x75, 0x6d, 0x70, 0x69, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x6d, 0x70, 0x69, 0x72, 0x65, 0x52, 0x06, 0x75,
	0x6d, 0x70, 0x69, 0x72, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x61, 0x74, 0x69, 0x6b, 0x64, 0x68, 0x61, 0x6e, 0x61, 0x76,
	0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x65, 0x2f, 0x62, 0x72, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x77,
	0x64, 0x65, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_umpire_proto_rawDescOnce sync.Once
	file_rpc_umpire_proto_rawDescData = file_rpc_umpire_proto_rawDesc
)

func file_rpc_umpire_proto_rawDescGZIP() []byte {
	file_rpc_umpire_proto_rawDescOnce.Do(func() {
		file_rpc_umpire_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_umpire_proto_rawDescData)
	})
	return file_rpc_umpire_proto_rawDescData
}

var file_rpc_umpire_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_umpire_proto_goTypes = []interface{}{
	(*CreateUmpireRequest)(nil),  // 0: grpc.CreateUmpireRequest
	(*CreateUmpireResponse)(nil), // 1: grpc.CreateUmpireResponse
	(*Umpire)(nil),               // 2: grpc.Umpire
}
var file_rpc_umpire_proto_depIdxs = []int32{
	2, // 0: grpc.CreateUmpireResponse.umpire:type_name -> grpc.Umpire
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_umpire_proto_init() }
func file_rpc_umpire_proto_init() {
	if File_rpc_umpire_proto != nil {
		return
	}
	file_umpire_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_umpire_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUmpireRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_umpire_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUmpireResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_umpire_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_umpire_proto_goTypes,
		DependencyIndexes: file_rpc_umpire_proto_depIdxs,
		MessageInfos:      file_rpc_umpire_proto_msgTypes,
	}.Build()
	File_rpc_umpire_proto = out.File
	file_rpc_umpire_proto_rawDesc = nil
	file_rpc_umpire_proto_goTypes = nil
	file_rpc_umpire_proto_depIdxs = nil
}
