// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: umpire.proto

package brownlowdev

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Umpire struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Fullname string `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Umpire) Reset() {
	*x = Umpire{}
	if protoimpl.UnsafeEnabled {
		mi := &file_umpire_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Umpire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Umpire) ProtoMessage() {}

func (x *Umpire) ProtoReflect() protoreflect.Message {
	mi := &file_umpire_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Umpire.ProtoReflect.Descriptor instead.
func (*Umpire) Descriptor() ([]byte, []int) {
	return file_umpire_proto_rawDescGZIP(), []int{0}
}

func (x *Umpire) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Umpire) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *Umpire) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_umpire_proto protoreflect.FileDescriptor

var file_umpire_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x75, 0x6d, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x67, 0x72, 0x70, 0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x06, 0x55, 0x6d, 0x70, 0x69, 0x72, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x61, 0x74,
	0x69, 0x6b, 0x64, 0x68, 0x61, 0x6e, 0x61, 0x76, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x65, 0x2f,
	0x62, 0x72, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x77, 0x64, 0x65, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_umpire_proto_rawDescOnce sync.Once
	file_umpire_proto_rawDescData = file_umpire_proto_rawDesc
)

func file_umpire_proto_rawDescGZIP() []byte {
	file_umpire_proto_rawDescOnce.Do(func() {
		file_umpire_proto_rawDescData = protoimpl.X.CompressGZIP(file_umpire_proto_rawDescData)
	})
	return file_umpire_proto_rawDescData
}

var file_umpire_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_umpire_proto_goTypes = []interface{}{
	(*Umpire)(nil), // 0: grpc.Umpire
}
var file_umpire_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_umpire_proto_init() }
func file_umpire_proto_init() {
	if File_umpire_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_umpire_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Umpire); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_umpire_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_umpire_proto_goTypes,
		DependencyIndexes: file_umpire_proto_depIdxs,
		MessageInfos:      file_umpire_proto_msgTypes,
	}.Build()
	File_umpire_proto = out.File
	file_umpire_proto_rawDesc = nil
	file_umpire_proto_goTypes = nil
	file_umpire_proto_depIdxs = nil
}
