package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"
	"graph-api/pkg/graph"
)

// CreateUmpire is the resolver for the createUmpire field.
func (r *mutationResolver) CreateUmpire(ctx context.Context, input graph.NewUmpire) (*graph.Umpire, error) {
	return r.res.CreateUmpire(ctx, input)
}
